### ISSUE TITLE
iOS 13.3 Support

### ISSUE THREAD

**Issue by StiviiK** [JeffResc/Meteoroid#3]
I just tried the tweak with iOS 13.3 on my iPhone 11 but it seems that the wallpaper is never loading.

**Comment by JeffResc** [comment]
I will look into this as soon as I have a device with a jailbreak myself. Hopefully the next version of Unc0ver will allow me to do so.

**Comment by StiviiK** [comment]
If you need any further information, I can try to provide them for you. 😄

**Comment by JeffResc** [comment]
Closing this as [v1.0.5](https://github.com/JeffResc/Meteoroid/releases/tag/v1.0.5) adds iOS 13 support. It has been submitted to Dynastic Repo and should be available shortly, enjoy! :)
